import { chromium, devices } from "@playwright/test";
const b = await chromium.launch();
const scr = "C:/Users/monum/AppData/Local/Temp/claude/d--Agentix-Project-myskinwise/4add9ff4-c830-4564-981d-1bec2029bfb6/scratchpad";
const ctx = await b.newContext({ ...devices["iPhone 13"] });
await ctx.addInitScript(()=>{try{sessionStorage.setItem("sw_voice_opened","1")}catch{}});
const p = await ctx.newPage();
await p.goto("http://localhost:3000/skin-check/analyzer", { waitUntil:"networkidle" });
await p.waitForTimeout(800);
await p.setInputFiles("input[type=file]", "public/images/brand/model-portrait-pink-bg.png");
await p.waitForTimeout(1200);
const consent = p.locator("input[type=checkbox]").first();
if (await consent.count()) await consent.check().catch(()=>{});
await p.getByRole("button",{name:/analyse my photo/i}).click().catch(()=>{});
await p.waitForSelector("button[aria-label*='—']",{timeout:30000}).catch(()=>{});
await p.waitForTimeout(800);
console.log("markers:", await p.locator("button[aria-label*='—']").count());
await p.locator("img[alt='The photo you submitted']").scrollIntoViewIfNeeded().catch(()=>{});
await p.screenshot({ path: scr+"/markers.png" });
await b.close();
