export type ImageAsset = { src: string; alt: string; width: number; height: number };

export const IMAGES = {
  logo: {
    src: "/images/logo.png",
    alt: "Skinwise logo, a rose-pink script wordmark",
    width: 313,
    height: 177,
  },
  heroModel: {
    src: "/images/hero-model.jpg",
    alt: "Woman with clear, healthy, glowing skin smiling gently against a warm brown studio backdrop",
    width: 1708,
    height: 2560,
  },
  bannerLongterm: {
    src: "/images/banner-longterm.jpg",
    alt: "Smiling woman gently touching her glowing cheeks beside the headline promising tailor-made solutions for long-term skin problems",
    width: 1920,
    height: 720,
  },
  bannerScience: {
    src: "/images/banner-science.jpg",
    alt: "Smiling woman with bare shoulders beside the headline about proven skin science renewing skin",
    width: 1920,
    height: 720,
  },
  package45Day: {
    src: "/images/package-45-day.jpg",
    alt: "Skinwise 45-day customised acne treatment bundle with cleanser, spray toner, and two cream jars",
    width: 1080,
    height: 1350,
  },
  package30Day: {
    src: "/images/package-30-day.jpg",
    alt: "Skinwise 30-day customised acne treatment bundle with cleanser bottle and two cream jars",
    width: 1080,
    height: 1350,
  },
  package15Day: {
    src: "/images/package-15-day.jpg",
    alt: "Skinwise 15-day customised acne treatment bundle with cleanser bottle and one cream jar",
    width: 1080,
    height: 1350,
  },
  concernRedness: {
    src: "/images/concern-redness.jpg",
    alt: "Extreme close-up of under-eye skin with visible redness and broken capillaries circled",
    width: 2560,
    height: 1280,
  },
  concernTexture: {
    src: "/images/concern-texture.jpg",
    alt: "Extreme close-up of dry, rough, textured skin with a problem area circled",
    width: 2560,
    height: 1280,
  },
  concernPores: {
    src: "/images/concern-pores.jpg",
    alt: "Close-up of a cheek and nose showing enlarged pores with a problem area circled",
    width: 2560,
    height: 1280,
  },
  concernBlemishes: {
    src: "/images/concern-blemishes.jpg",
    alt: "Close-up of cheek and lip area showing blemishes and enlarged pores with a problem area circled",
    width: 2560,
    height: 1280,
  },
  model1: {
    src: "/images/model-1.jpg",
    alt: "Woman looking upward and smiling with both hands framing her clear, glowing face",
    width: 1440,
    height: 2560,
  },
  galleryLaunchEvent: {
    src: "/images/gallery-launch-event.jpg",
    alt: "Group of four people celebrating at a Skinwise product launch event with balloons, flowers, and a display table",
    width: 1080,
    height: 1350,
  },
  blogSkincareHabits: {
    src: "/images/blog-skincare-habits.png",
    alt: "Close-up of a smiling woman touching her cheeks, illustrating an article on skincare habits",
    width: 1200,
    height: 600,
  },

  // --- Brand assets curated from myskinwise.com (see public/images/brand) ---

  leafMotif: {
    src: "/images/brand/leaf-motif.png",
    alt: "Decorative botanical leaf line-art corner flourish",
    width: 300,
    height: 201,
  },
  brandHeroLeafLongterm: {
    src: "/images/brand/hero-leaf-longterm.jpg",
    alt: "Smiling woman with hands framing her glowing cheeks in front of a soft pink botanical leaf line-art backdrop, beside the headline resolving long-term skin problems with tailor-made solutions",
    width: 1920,
    height: 720,
  },
  brandHeroLeafScience: {
    src: "/images/brand/hero-leaf-science.jpg",
    alt: "Smiling woman with bare shoulders in front of a soft pink botanical leaf line-art backdrop, beside the headline about proven skin science renewing skin",
    width: 1920,
    height: 720,
  },
  founderAnant: {
    src: "/images/brand/founder-anant-sanadhya.png",
    alt: "Anant Sanadhya, Skinwise Founder and CEO, in a brown three-piece suit",
    width: 746,
    height: 1024,
  },
  heroModelPink: {
    src: "/images/brand/model-hero-pink-cutout.png",
    alt: "Cutout photo of a smiling woman in a pink top framing her face with both hands, clear glowing skin",
    width: 1024,
    height: 1536,
  },
  heroModelWhite: {
    src: "/images/brand/model-hero-white-cutout.png",
    alt: "Cutout photo of a woman with closed eyes gently cupping her own face, clear glowing skin",
    width: 966,
    height: 1024,
  },
  heroModelPortrait: {
    src: "/images/brand/model-portrait-pink-bg.png",
    alt: "Close-up beauty portrait of a smiling woman with clear, glowing skin and bare shoulders",
    width: 1536,
    height: 1382,
  },
  modelCutoutSmall: {
    src: "/images/brand/model-cutout-curly.png",
    alt: "Small cutout headshot of a smiling woman with curly hair looking over her shoulder",
    width: 300,
    height: 242,
  },
  ingredientVitaminC: {
    src: "/images/brand/ingredient-vitamin-c.jpg",
    alt: "Golden Vitamin C serum droplet: brightens skin and reduces dark spots",
    width: 1414,
    height: 2000,
  },
  ingredientKojicAcid: {
    src: "/images/brand/ingredient-kojic-acid.jpg",
    alt: "Kojic Acid gel in a petri dish: lightens pigmentation and evens skin tone",
    width: 1414,
    height: 2000,
  },
  ingredientRetinol: {
    src: "/images/brand/ingredient-retinol.jpg",
    alt: "Retinol disc under magnification: speeds up cell turnover and fades dark spots",
    width: 1414,
    height: 2000,
  },
  ingredientAlphaArbutin: {
    src: "/images/brand/ingredient-alpha-arbutin.jpg",
    alt: "Alpha Arbutin cream swatch with a sprig of honeysuckle flowers: fades hyperpigmentation gently",
    width: 1414,
    height: 2000,
  },
  ingredientNiacinamide: {
    src: "/images/brand/ingredient-niacinamide.jpg",
    alt: "Niacinamide gel on a plate: controls oil production and soothes inflammation",
    width: 1414,
    height: 2000,
  },
  ingredientSalicylicAcid: {
    src: "/images/brand/ingredient-salicylic-acid.jpg",
    alt: "Salicylic Acid gel swatch: unclogs pores and reduces blackheads and whiteheads",
    width: 1414,
    height: 2000,
  },
  beforeAfterAcnePayal: {
    src: "/images/brand/before-after-acne-payal.jpg",
    alt: "Before and after photos of Payal, 29, Haryana, showing reduced acne on her cheek after 56 days",
    width: 821,
    height: 1024,
  },
  beforeAfterAcneDivya: {
    src: "/images/brand/before-after-acne-divya.jpg",
    alt: "Before and after photos of Divya, 28, Rajasthan, showing reduced acne on her jaw after 48 days",
    width: 821,
    height: 1024,
  },
  beforeAfterAcneTanu: {
    src: "/images/brand/before-after-acne-tanu.jpg",
    alt: "Before and after photos of Tanu, 30, Uttarakhand, showing reduced acne on her cheek after 70 days",
    width: 821,
    height: 1024,
  },
  beforeAfterAcneAisha: {
    src: "/images/brand/before-after-acne-aisha.jpg",
    alt: "Before and after photos of Aisha, 27, Bihar, showing reduced acne on her cheek after 48 days",
    width: 821,
    height: 1024,
  },
  beforeAfterPigmentationAnu: {
    src: "/images/brand/before-after-pigmentation-anu.jpg",
    alt: "Before and after photos of Anu, 37, Surat, Gujarat, showing faded pigmentation on her cheek after 63 days",
    width: 821,
    height: 1024,
  },
  beforeAfterOtherKiran: {
    src: "/images/brand/before-after-other-kiran.jpg",
    alt: "Before and after photos of Kiran, 29, Delhi, showing smoother skin texture near her mouth after 43 days",
    width: 821,
    height: 1024,
  },
  beforeAfterOtherShruti: {
    src: "/images/brand/before-after-other-shruti.jpg",
    alt: "Before and after photos of Shruti, 26, Delhi, showing improved skin texture on her cheek after 28 days",
    width: 821,
    height: 1024,
  },
  beforeAfterOtherNisha: {
    src: "/images/brand/before-after-other-nisha.jpg",
    alt: "Before and after photos of Nisha, 32, Delhi, showing reduced pores around her nose after 28 days",
    width: 821,
    height: 1024,
  },
  avatarClearSkin: {
    src: "/images/brand/avatar-clear-skin.png",
    alt: "Illustrated avatar of a woman with clear, even skin",
    width: 1024,
    height: 1024,
  },
  avatarPigmentation: {
    src: "/images/brand/avatar-pigmentation.png",
    alt: "Illustrated avatar of a woman with pigmentation patches on her cheeks",
    width: 1024,
    height: 1024,
  },
  avatarAcne: {
    src: "/images/brand/avatar-acne.png",
    alt: "Illustrated avatar of a woman with acne breakouts on her forehead, cheeks, and neck",
    width: 1024,
    height: 1024,
  },
  illustrationProcessSteps: {
    src: "/images/brand/illustration-process-steps.png",
    alt: "Four-step illustration: expert skin analysis, customised solution, root-cause treatment, and continuous support",
    width: 1024,
    height: 1024,
  },
  illustrationTransformRoutine: {
    src: "/images/brand/illustration-transform-routine.jpg",
    alt: "A dropper releasing a droplet of serum above an open glass bottle, illustrating a transformed skincare routine",
    width: 240,
    height: 300,
  },
  productBottlesWhite: {
    src: "/images/brand/product-bottles-white.jpg",
    alt: "Skinwise cleanser, toner spray, and two cream jars on a water-speckled grey backdrop",
    width: 1024,
    height: 1024,
  },
  productBottlesWhiteAlt: {
    src: "/images/brand/product-bottles-white-alt.jpg",
    alt: "Skinwise cleanser bottle and two stacked cream jars on a water-speckled grey backdrop",
    width: 1024,
    height: 1024,
  },
  productBottlesPink: {
    src: "/images/brand/product-bottles-pink.jpg",
    alt: "Skinwise cleanser, toner spray, and two cream jars with rose-pink labels on a water-speckled grey backdrop",
    width: 1080,
    height: 1080,
  },
  safetyBadgesGrid: {
    src: "/images/brand/safety-badges-grid.jpg",
    alt: "Four safety badges in a grid: Clinically Proven, Dermatologist-Tested, No AI Based, and Cruelty-Free",
    width: 1024,
    height: 1024,
  },
  safetyBadgesRow: {
    src: "/images/brand/safety-badges-row.jpg",
    alt: "Four safety badges in a row: Clinically Proven, Dermatologist-Tested, No AI Based, and Cruelty-Free",
    width: 1024,
    height: 273,
  },
  concernPigmentationOutline: {
    src: "/images/brand/concern-pigmentation-outline.jpg",
    alt: "Close-up of a face with a hand-drawn outline marking a hyperpigmentation patch on the cheek",
    width: 1500,
    height: 1498,
  },
  concernPigmentationSquare: {
    src: "/images/brand/concern-pigmentation-square.jpg",
    alt: "Close-up of a cheek with a square marker highlighting a hyperpigmentation patch",
    width: 1024,
    height: 730,
  },
  skinZoneMap: {
    src: "/images/brand/skin-zone-map.jpg",
    alt: "Diagram of a face mapping breakout zones to causes: forehead to stress and dehydration, cheeks to bacteria and pollution, chin and jaw to hormones",
    width: 268,
    height: 300,
  },
} as const satisfies Record<string, ImageAsset>;

export type ImageKey = keyof typeof IMAGES;
